In [5]:
# 원-핫 인코딩
from konlpy.tag import Komoran
import numpy as np

komoran = Komoran()
text = '나는 자연어 처리를 배운다'

# 명사만 추출하기
nouns = komoran.nouns(text)
print(nouns)

# 단어 사전 생성 및 인덱스 부여
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

# 원-핫 인코딩
# 원-핫 벡터 차원의 크기 결정 > 단어 사전의 크기가 원-핫 벡터의 크기가 되기 떄문
targets = list(dics.values())
one_hot_targets = np.eye(len(dics))[targets]
print(one_hot_targets)

['자연어', '처리']
{'자연어': 0, '처리': 1}
[[1. 0.]
 [0. 1.]]


In [10]:
from konlpy.tag import Okt
import numpy as np

okt = Okt()
text = '나는 자연어 처리를 배운다'

nouns = okt.nouns(text)
print(nouns)

# 단어 사전 생성 및 인덱스 부여
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

# 원-핫 인코딩
# 원-핫 벡터 차원의 크기 결정 > 단어 사전의 크기가 원-핫 벡터의 크기가 되기 떄문
targets = list(dics.values())
one_hot_targets = np.eye(len(dics))[targets]
print(one_hot_targets)

['나', '자연어', '처리']
{'나': 0, '자연어': 1, '처리': 2}
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
